# Generated by Django 3.2.5 on 2021-11-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0004_alter_storagevariant_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagevariant',
            name='ramUnit',
            field=models.CharField(choices=[('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte')], default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='storagevariant',
            name='storageUnit',
            field=models.CharField(choices=[('TB', 'Terabyte'), ('GB', 'Gigabyte'), ('MB', 'Megabyte')], default='GB', max_length=2),
        ),
    ]
