# Generated by Django 3.2.5 on 2021-11-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0006_cart_productsincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MobilesHQ_main.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='productsInCart',
        ),
    ]
