# Generated by Django 3.2.5 on 2021-12-01 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0007_auto_20211125_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MobilesHQ_main.colorvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MobilesHQ_main.storagevariant'),
            preserve_default=False,
        ),
    ]
