# Generated by Django 3.2.5 on 2021-12-16 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0008_auto_20211201_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='color',
        ),
        migrations.DeleteModel(
            name='colorVariant',
        ),
    ]
