# Generated by Django 3.2.5 on 2021-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0009_auto_20211216_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(default='Place, Holder', max_length=128),
            preserve_default=False,
        ),
    ]
