# Generated by Django 3.2.5 on 2021-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0010_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='storage',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='storageVariant',
        ),
    ]
