# Generated by Django 3.2.5 on 2021-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobilesHQ_main', '0011_auto_20211216_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='storage',
            field=models.CharField(default='temp', max_length=64),
            preserve_default=False,
        ),
    ]
